### ISSUE TITLE
Idea: Ronald McDonald sprite item names

### ISSUE THREAD

**Issue by VirtueAvatar** [theonlydude/varia_custom_sprites#1]
Draft list of names below, there's potential for some better name suggestions. Naming is hard. 
Would have liked to have used mcchicken or fries or hot apple pie (apple pie bomb was not great), but where do they fit and are they better than what's below?

'RENAMEronald.ips': {
'Varia': 'hotcakes',
'Gravity': 'grimace',
'Charge': 'cheeseburger',
'Ice': 'ice cola',
'Wave': 'wrap',
'Spazer': 'salad',
'Plasma': 'quarter pounder',
'HiJump': 'hash jump browns',
'SpeedBooster': 'fast food',
'SpaceJump': 'silly joke',
'Morph': 'ball pit',
'Bomb': 'chicken mcnuggets',
'SpringBall': 'juggling ball',
'ScrewAttack': 'sundae attack',
'Missile': 'bacon & egg mcmuffin', --or bacon mcmuffin
'Super': 'sausage mcmuffin',
'PowerBomb': 'big mac',
'Grapple': 'grab & go',
'XRayScope': 'hamburglar mask',
'Reserve': 'happy meal toy',
'ETank': 'happy meal'
},

**Comment by theonlydude** [comment]
custom names added. 
thank you.
