### ISSUE TITLE
Custom_Parasite_Queen_v1.0.nspc does not play when injected in super metroid

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [theonlydude/varia_custom_sprites#3]
the spc works though

**Comment by theonlydude** [comment]
hello,
this song is in the "Memory Violation" group and as such is not displayed in the customizer:
    "Parasite Queen (Custom)": {
        "nspc_path": "MMC_Server/Custom_Parasite_Queen_v1.0.nspc",
        "track_index": 0,
        "original_author": "Kenji Yamamoto",
        "port_author": "Albert V",
        "description": "Echo buffer must be set seperate!",
        "group": "Memory Violation",
        "spc_path": "MMC_Server/Custom_Parasite_Queen_v1.0.spc"
    },
